### ISSUE TITLE
Wasm build fails

### ISSUE THREAD

**Issue by sanket1729** [BlockstreamResearch/rust-secp256k1-zkp#47]
See: https://github.com/rust-bitcoin/rust-secp256k1/issues/419 for more context

**Comment by cryptoquick** [comment]
It looks like [this PR](https://github.com/rust-bitcoin/rust-secp256k1/pull/421) was merged a couple days after the latest release of this library. It shouldn't be too much additional work to get this compiling on wasm32, correct?

**Comment by apoelstra** [comment]
So, the relevant bug was avoided in 7055f4f463c61d4565e4208cf1a26b600832df09 (Dec 2020) which simply deletes the offending symbols from secp-zkp-sys, preferring instead to import them from secp-sys. So when https://github.com/rust-bitcoin/rust-secp256k1/pull/419 (March 2021) was merged that fix should've propagated to here.

So I think we could've re-enabled WASM CI tests a long time ago.

I will backport https://github.com/rust-bitcoin/rust-secp256k1/pull/422 to bring in some other CI improvements.

**Comment by apoelstra** [comment]
BTW the main fix in #422 (using `-e` and not using `&&`) was implemented here already in https://github.com/ElementsProject/rust-secp256k1-zkp/pull/25 (July 2021)

**Comment by cryptoquick** [comment]
I see, thank you for the explanation!
