### ISSUE TITLE
remove `--all` in `contrib/test.sh`

### ISSUE THREAD

**Issue by RCasatta** [BlockstreamResearch/rust-secp256k1-zkp#77]
From the cargo doc:

`--all               Alias for --workspace (deprecated)`

There is no workspace so the flag isn't needed

**Comment by apoelstra** [comment]
I think we should leave it, in case we add workspaces in the future, and in case other projects copy our contrib/test.sh.

**Comment by RCasatta** [comment]
Ok, but I don't think it's the best choice, we even had a subtle issue regarding `--all` in CI but I don't remember the repo.

**Comment by apoelstra** [comment]
cargo has `--all`, `--all-targets`, `--all-features`, `--workspace` and probably others. It is true that no combination of these will actually make cargo test all features and all targets, and that this has caused us continual grief with CI in multiple projects.

But I think, the next time we find such an issue, it'll save us a bit of time to already have `--all` present.

**Comment by RCasatta** [comment]
> but I don't remember the repo.

I was referring to [this](https://github.com/ElementsProject/rust-elements/commit/a8f4c8c76f43f61e783b05c9d117c2fae4321763)
